name: Release

on:
  release:
    types: [created]

jobs:

  linux:
    name: Ubuntu 14.04
    runs-on: ubuntu-latest
    steps:
      - name: Parse release description
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          script: |
            function parseRef(s) {
              let pattern = /^(?:ref(?:erence)?|commit|tag):\s+(.*)$/gmi;
              let matches = pattern.exec(s);
              if (!matches || matches.length < 1) return "master";

              return matches[1];
            }

            function parseBuild(s) {
              let pattern = /^(?:builds?|platforms?|OS(?:es)?):\s+(?:(appimage|linux|win(?:dows)?)(?:,\s+(appimage|linux|win(?:dows)?))*)$/gmi;
              let matches = pattern.exec(s);
              let all = ["appimage", "windows"];
              if (!matches || matches.length < 1) return all;

              let builds = [];
              for (let i = 1; i < matches.length; i++) {
                if (!matches[i]) continue;

                switch (matches[i].toLowerCase()) {
                  case "appimage":
                  case "windows":
                    builds.push(matches[i].toLowerCase());
                    break;

                  case "win":
                    builds.push("windows");
                    break;
                  
                  case "linux":
                    builds.push("appimage");
                    break;

                  default:
                    console.warn("Unknown build: " + matches[i]);
                }
              }

              if (!builds.length) return all;
              return builds;
            }

            console.log("Current description:");
            console.log(context.payload.release.body);

            let requestParams = {
              ref: parseRef(context.payload.release.body),
              builds: parseBuild(context.payload.release.body),
              upload_url: context.payload.release.upload_url
            };
            
            console.log("Parsed parameters:");
            console.log(requestParams);

            github.repos.createDispatchEvent({
              owner: 'kotatogram',
              repo: 'kotatogram-desktop-builds',
              event_type: 'build'
              client_payload: requestParams,
            });

