name: Release

on:
  release:
    types: [created]

jobs:

  parse:
    name: Parse release
    runs-on: ubuntu-latest
    steps:
      - name: Clone scripts.
        uses: actions/checkout@v2
      - name: Parse release description
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.RELEASE_TOKEN }}
          script: |
            const path = require('path');
            const scriptPath = path.resolve('./scripts/option_parser.js');
            require(scriptPath)({github, context});
